version: 2

defaults: &defaults
  working_directory: ~/repo

jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/node:14.18.0
      - image: bitnami/redis:latest
        port:
          6379: 6379
        environment:
          ALLOW_EMPTY_PASSWORD: yes

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: yarn run build
      - run:
          name: Lint
          command: yarn run lint
      - run:
          name: Test
          command: yarn run test
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    <<: *defaults
    docker:
      - image: circleci/node:14.18.0
    steps:
      # Reuse the workspace from the build job
      - attach_workspace:
          at: .
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish
          command: npx lerna publish from-package --yes

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
